### PR TITLE
Add Builder for SpdxListedLicense

### PR DESCRIPTION
**Pull request by amCap1712**

### CODE REVIEW

**Review by goneall — CHANGES_REQUESTED** [review]
@amCap1712 Thanks for contributing the builder for this class.

Two requested changes:
- Please add a constructor which take the builder as a parameter - this is the pattern we are following for the other model classes with builder.  Example here: https://github.com/spdx/Spdx-Java-Library/blob/4a11d3c43a32ff0d13793427cfe3b3608da76a52/src/main/java/org/spdx/library/model/SpdxPackage.java#L88
- Add JavaDoc comments for the constructor and methods that describe the variables.  You can copy the text from other setter or constructor methods in this class

**Comment by amCap1712** [comment]
@goneall Thanks for pointing out the issues. I had actually forgotten to push all the work.

**Review by goneall — CHANGES_REQUESTED** [review]
One more request - If you could add a constructor to the builder which takes all of the required parameters.  This is a pattern I've been following to help ensure required parameters are always included.

In this case, the only required parameters as ID, name and text.

**Review by goneall — APPROVED** [review]
LGTM

**Comment by goneall** [comment]
Thanks @amCap1712 - The changes look good.  Let me know if you have any other changes planned, otherwise I'll go ahead and merge.

**Comment by amCap1712** [comment]
I do not have further changes planned for this builder. Thanks again for the review.

**Pull request merged**
