### PR TITLE
Preserve order in collections.

### PR DESCRIPTION
**Pull request by carmenerre**
This MR tries to solve https://github.com/spdx/Spdx-Java-Library/issues/146

It replaces the use of `HashMap` with `LinkedHashMap`, which preserves the performance improvement done in https://github.com/spdx/Spdx-Java-Library/pull/144 but keeps the insertion order in collections.

Because LinkedHashMap is not synchronized, it has been wrapped using `Collections.synchronizedMap` method.

### CODE REVIEW

**Review by goneall — APPROVED** [review]
Thanks @carmenerre - great improvement to the code.

**Comment by beltran-rubo** [comment]
@goneall any ETA for a new release in June? This is a great improvement, thanks.

**Comment by goneall** [comment]
@beltran-rubo - would you want a complete release of all the java tools or just this library?  I could spin the library version pretty quickly if it helps.  Otherwise, it will probably be towards the end of June for a release of the complete set of Java tools as I'm working on a release of the online tools over the next week or two.

**Comment by beltran-rubo** [comment]
We are using the Java library itself, it would be great to get it sooner than later including this improvement. Thanks!

**Comment by goneall** [comment]
> We are using the Java library itself, it would be great to get it sooner than later including this improvement. Thanks!

In that case I'll plan on producing a release of this library over the next couple of days.

**Comment by beltran-rubo** [comment]
Thanks! Still a bit early to move to version 3 on our side but we can help with the revision and testing.

**Pull request merged**
