### PR TITLE
Add unit tests that exercise issue #234

### PR DESCRIPTION
**Pull request by pmonks**
This PR adds unit tests that exercise issue #234.  They're (deliberately) minimal, since license comparison is expensive and already a sizable portion of the runtime of the unit tests, but they at least show what's going on with that issue as of v1.11 of the library.

Note: the tests are failing because this PR only adds (previously missing) unit tests to demonstrate issue #234, but not logic to fix it.

### CODE REVIEW

**Comment by goneall** [comment]
Thanks @pmonks - creating unit tests will help in diagnosing/fixing the issues.

It may be a while before I can look at these issues - I'm prioritizing getting the SPDX 3.0 supported.

**Comment by pmonks** [comment]
@goneall yep absolutely no problem - I know just how busy you've been with the 3.0 release and updating the library to match!

**Comment by pmonks** [comment]
@goneall I believe this PR can be closed without merging, as the changes here were merged as part of PR #249.

**Comment by goneall** [comment]
Thanks @pmonks - closing the issue

**Pull request closed without merging**
