### PR TITLE
Fail a license compare if there is text following a matching license

### PR DESCRIPTION
**Pull request by goneall**
When using the `LicenseCompareHelper.isTextStandardLicense` and there is text in the compare license text following a valid license text match, fail the license compare.

This issue was originally raised in https://github.com/spdx/license-list-XML/issues/1583

Signed-off-by: Gary O'Neall <gary@sourceauditor.com>

### CODE REVIEW

**Comment by goneall** [comment]
Note that this fix is not yet complete.  It is failing one of the regression tests where a license template ends with optional text.

**Comment by goneall** [comment]
The following license fail to match against the text after this fix and should be investigated and resolved:

- [ ] Python-2.0.1 - Fix is underway per https://github.com/spdx/license-list-XML/issues/1583#issuecomment-1226187475
- [ ] HPND - Pull request submitted: https://github.com/spdx/license-list-XML/pull/1587
- [ ] APSL-2.0 - This template and text looks correct, this could be an issue with the license matcher
- [ ] APL-1.0 - This template and text looks correct, this could be an issue with the license matcher
- [ ] CPAL-1.0 - This template and text looks correct, this could be an issue with the license matcher
- [ ] Fair - Extra line at the end of the test file - Pull request submitted https://github.com/spdx/license-list-XML/pull/1589
- [ ] GFDL-1.1-invariants-or-later - Note that the GFDL-1.1-invariants-only matches.  The templates differ in that the last optional in the or-later version has a bunch of extra matching alt text.  There is most likely an error on one of these regexes.
- [ ] MPL-2.0-no-copyleft-exception - This template and text looks correct, this could be an issue with the license matcher
- [ ] OSET-PL-2.1 - This template and text looks correct, this could be an issue with the license matcher
- [ ] SGI-B-1.0 - This template and text looks correct, this could be an issue with the license matcher
- [ ] SGI-B-1.1 - This template and text looks correct, this could be an issue with the license matcher
- [ ] Spencer-86 - Extra line in the test file - issue submitted: https://github.com/spdx/license-list-XML/issues/1590
- [ ] SPL-1.0 - This template and text looks correct, this could be an issue with the license matcher
- [ ] SSPL-1.0 - Submitted issue: https://github.com/spdx/license-list-XML/issues/1591
- [ ] SugarCRM-1.1.3 - This template and text looks correct, this could be an issue with the license matcher
- [ ] gnu-javamail-exception - Created pull request

**Comment by goneall** [comment]
Note that almost all of the test failures due to the license matcher has an Optional at the very end of the XML file (most are optional Exhibits).  Also note that the error indicates the missmatch is the first word after the start of the optional text.

**Comment by goneall** [comment]
@swinslow - looks like all of the errors in the LicenseListXML comparison are due to errors in the XML markups.

I fixed all exception  GFDL-1.1-invariants-or-later, SGI-B-1.0, and SGI-B-1.1.  For these, I think we should just remove the extra matching stuff in the last optional section. It would probably take 3-4 hours to get these more complex markups to work.  Let me know what you think.

**Comment by swinslow** [comment]
Thanks @goneall! This is awesome. Thanks for submitting all the fixes in the license-list-XML repo.

I will try to take a closer look at this soon. I'm about to be offline for a while, but will aim to review the PRs and the three remaining ones that you mentioned when I'm able to do so.

**Pull request merged**
