### PR TITLE
[Issue 105] Fix ModelObject#equivalent not being symmetric

### PR DESCRIPTION
**Pull request by nicoweidner**
Fixes https://github.com/spdx/Spdx-Java-Library/issues/105
Note: After making my changes, `ModelObjectTest#testClone` failed. I removed the line testing that `result.equivalent(gmo)` because my current understanding is that `clone` only creates a copy with the same identifiers in a new store, but without the properties populated; `copyFrom` seems to be the method to use for copying properties. Hence the check that the objects are equivalent is misplaced in that test (and wasn't noticed because of the bug fixed in this PR)

Signed-off-by: Nicolaus Weidner <nicolaus.weidner@tngtech.com>

### CODE REVIEW

**Comment by goneall** [comment]
@nicoweidner Thanks for the PR!

For the clone function, I would still expect the 2 objects to be equivalent.  Do we know what the call to equivalent is failing (or working prior to the change)?

**Comment by nicoweidner** [comment]
> @nicoweidner Thanks for the PR!
> 
> For the `clone` function, I would still expect the 2 objects to be equivalent. The `clone` function does copy the properties. The difference between `clone` and `copyFrom` is that `copyFrom` does not create a new `ModelObject`, it copies properties from a different `ModelObject` to itself. Do we know why the call to equivalent is failing (or working prior to the change)?

@goneall Now I am confused again about clone :sweat_smile: . My reasoning was this: In [the clone method](https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/library/model/ModelObject.java#L993-L999), a new `ModelObject` is created using a different store. Following the code, this just calls the corresponding constructor with the store that was passed in. So all properties of the new cloned object will be taken from the model store that was passed in, not from the model store of the original object. Am I wrong here?

The test `testClone` was failing becaues the two objects were not equivalent at all. The input object `gmo` has 23 properties which are populated [in this line](https://github.com/spdx/Spdx-Java-Library/blob/master/src/test/java/org/spdx/library/model/ModelObjectTest.java#L660). The cloned object `result` has no properties at all. This strengthened my belief that the conclusion above was correct...

The reason the test passed so far is exactly the bug fixed in this PR: The assertion was written in the form `result.equivalent(gmo)`. In this case, properties only present on `gmo` were simply ignored during the comparison.


On a different note, I noticed one bug I introduced (erroneous early return) and several test failures (I only executed `ModelObjectTest` locally :flushed: ). I will fix those. I assume it is okay to squash and force-push on feature branches? Then I would squash it into 4ca128fd2799834e5e4d7ea2dcbd3279e2604696 because it should have been included there in the first place.

**Comment by nicoweidner** [comment]
I pushed some changes that should fix CI. In my effort to simplify the logic, I accidentally broke some edge cases :grimacing: . Luckily, some test caught it; I also added specific unit tests for those cases (empty model collections and noassertion values, which are treated like null in comparisons).

As mentioned before, the additional 4 commits should all be part of the initial commit. @goneall I will wait for a quick opinion before squashing them and force-pushing.

**Comment by nicoweidner** [comment]
@goneall One further question: I noticed that in [the propertyValuesEquivalent](https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/library/model/ModelObject.java#L822-L867) method (which is called when comparing two `ModelObject`s for equivalence), `noassertion` is not considered. Is this by mistake?

This would only be relevant in specific situations I believe (and I can't tell at this point whether they can actually occur, but still...). Let's say we are comparing `property1` between `object1` and `object2`:
 - first value is `NOASSERTION`, second value is missing (this shouldn't occur since model store reported a nonempty value, but we still check for it)
 - first value is `NOASSERTION`, second value is an empty `ModelCollection` (not sure if `NOASSERTION` is valid when the property contains a list)

**Comment by nicoweidner** [comment]
I created https://github.com/spdx/Spdx-Java-Library/issues/107 to discuss the `clone` issue. Then I would leave this PR as is, with the `equivalent` check removed from the test for `clone`. The linked issue can add it back in if we decide to change the clone method.

**Comment by nicoweidner** [comment]
Ok, commits are squashed, should be good to go now unless someone finds another bug :-)

(the small refactor commit was squashed into the others since it would have been some effort to separate it, and it only changed a few lines anyway)

**Comment by goneall** [comment]
Thanks @nicoweidner

**Pull request merged**
