### PR TITLE
Add 'var' text support for matching within text

### LINKED ISSUE #155: Pre-release code: inconsistent behaviour between matchingStandardLicenseIds and matchingStandardLicenseIdsWithinText
Note: this issue references pre-release code in 1.1.5-SNAPSHOT.

It is my understanding that when `org.spdx.utility.compare.LicenseCompareHelper.matchingStandardLicenseIds()` produces a non-null / non-empty result on a given input, `org.spdx.utility.compare.LicenseCompareHelper.matchingStandardLicenseIdsWithinText()` should produce that same output (albeit in a single-entry list) for that same input, but that's not always happening.

For example I tested both methods with [this license text](https://raw.githubusercontent.com/commonmark/commonmark-java/main/LICENSE.txt), and the former (correctly) returns `"BSD-2-Clause"`, while the latter returns `null`.

Perhaps this should be fixed prior to the release of 1.1.5, and more unit tests added that compare the outputs of the latter method against the former, given the same (single license) input texts?

### PR DESCRIPTION
**Pull request by goneall**
Fixes #155

Note: This change introduces a severe performance issue for some licenses - noteably GPL3

### CODE REVIEW

**Comment by goneall** [comment]
@pmonks Try out the code in this branch.  It's still slow, but it is fast enough that the CI doesn't time out.  I'm curious if you see any problems with this fix - it is a bit complicated so I wouldn't be surprised if I broke something.

Some of the `alt` regular expressions in the license-list-XML source directories are inefficient.  I plan on submitting a PR sometime over the next week or two which should help the performance once the changes are accepted and published.

I'm thinking we comment out some of the unit tests so it doesn't take so long.

**Comment by pmonks** [comment]
@goneall I ran it with the handful of license texts I'm currently testing with (see below), and it worked as expected* for all but one of them (which is a lot better than before!).

License texts which worked as I expected (equivalent results from both `matchingStandardLicenseIds` and `matchingStandardLicenseIdsWithinText`): 
* [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0.txt)
* [GPL-3.0](https://www.gnu.org/licenses/gpl-3.0.txt)
* [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode.txt)
* [BSD-2-Clause (Atlassian)](https://raw.githubusercontent.com/commonmark/commonmark-java/main/LICENSE.txt)

License text which didn't work as I expected:
* [MPL-2.0](https://www.mozilla.org/media/MPL/2.0/index.txt): `matchingStandardLicenseIds` returned `["MPL-2.0-no-copyleft-exception", "MPL-2.0"]` (which looks correct to me) while `matchingStandardLicenseIdsWithinText` returned `null` (which seems quite wrong to me).

> I'm thinking we comment out some of the unit tests so it doesn't take so long.

Yeah definitely worth making them optional in some way, as performance of these methods could become a problem with a larger number of unit tests.

It's a bit hacky (though perhaps slightly less hacky than comments?), but perhaps a static boolean at the top of the unit test class that controls whether all unit tests are run or not (i.e. with an `if` block dependent on that boolean inline, conditionally evaluating a lot of the unit tests)?  It could default to false, but allow a developer to set it to true, perhaps via an environment variable; e.g.:
```java
static boolean RUN_SLOW_TESTS = System.getenv("SPDXJL_RUN_SLOW_TESTS") == null ? false : true;
... later in the code ...
    ... a few select slow tests go here ...
    if (RUN_SLOW_TESTS) {
        ... lots more slow tests go here ...
    }
```

I'm not up to date on whether using environment variables like this is considered "acceptable" for conditional Java unit testing, or if there's a more idiomatic alternative...

**Comment by goneall** [comment]
@pmonks I looked into why the MPL-2.0 text was failing.  It is due to the use of underlines (`-------` and `======`) as well as some stars put around the text.  These are not currently handled in the "find X within text" methods.

**Comment by goneall** [comment]
@pmonks I just updated the algorithm to remove the comment chars - this should fix the MPL matches.

**Comment by goneall** [comment]
@pmonks I took your advice and added a system variable `SPDX_JAVA_LIB_RUN_SLOW_TESTS` when set to true (e.g. `SPDX_JAVA_LIB_RUN_SLOW_TESTS=true`) will run the slow tests.  If it is missing or set to anything other than `true`, the long tests won't be run.

**Comment by pmonks** [comment]
@goneall I just updated to rev cffcbf9 (but see below) and retested with that [MPL-2 text](https://www.mozilla.org/media/MPL/2.0/index.txt), and confusingly I'm now seeing `org.spdx.utility.compare.LicenseCompareHelper.matchingStandardLicenseIds()` return `null` (previously it returned `["MPL-2.0-no-copyleft-exception", "MPL-2.0"]`), and `org.spdx.utility.compare.LicenseCompareHelper.matchingStandardLicenseIdsWithinText()` is now returning `["MPL-2.0-no-copyleft-exception" "MPL-2.0"]` (previously it returned `null`).  I believe both of these results should be `["MPL-2.0-no-copyleft-exception"]`.

I've done a little bit of messing about with my local Maven repository in case I'm not running against the copy of the code I _think_ I'm running against, but I haven't fully exhausted all the possibilities there (i.e. nuked the entire thing and forced Maven to re-download the internet).  I'll do that tomorrow just to fully rule out that possible explanation, though the fact that the behaviour changed from my previous attempt suggests it did download _something_ new (though whether it's the absolute latest & greatest I have yet to establish beyond all reasonable doubt).

**Comment by goneall** [comment]
@pmonks - I'm getting the same result.  I must have broken `matchingStandardLicenseIds()` with my previous commits.  I'll look into it.

**Comment by goneall** [comment]
@pmonks This has now been fixed with PR #160

**Comment by pmonks** [comment]
@goneall thanks for the updates! Here are the results of my latest testing (apologies for lack of inline formatting - it appears GitHub doesn't support that within tables).

Key:
✅ = result is as I expected
❌ = result is not what I expected

<table>
<tr>
  <th>License
  <th>License text source
  <th>Result from matchingStandardLicenseIdsWithinText()
  <th>Result from matchingStandardLicenseIds()
<tr>
	<td>Apache-2.0
    <td>https://www.apache.org/licenses/LICENSE-2.0.txt
	<td>✅ ["Apache-2.0"]
	<td>✅ ["Apache-2.0"] 
<tr>
	<td>GPL-3.0
    <td>https://www.gnu.org/licenses/gpl-3.0.txt
	<td>✅ ["GPL-3.0-only" "GPL-3.0" "GPL-3.0-or-later" "GPL-3.0+"]
	<td>✅ ["GPL-3.0-only" "GPL-3.0" "GPL-3.0-or-later" "GPL-3.0+"]
<tr>
	<td>CC-BY-4.0
    <td>https://creativecommons.org/licenses/by/4.0/legalcode.txt
	<td>❌ []
	<td>❌ []
<tr>
	<td>MPL-2.0
    <td>https://www.mozilla.org/media/MPL/2.0/index.txt
	<td>❌ ["MPL-2.0-no-copyleft-exception" "MPL-2.0"]

I believe this should be ["MPL-2.0-no-copyleft-exception"] only.
	<td>❌ ["MPL-2.0-no-copyleft-exception" "MPL-2.0"]
I believe this should be ["MPL-2.0-no-copyleft-exception"] only.
<tr>
	<td>BSD-2-Clause (Atlassian)
    <td>https://raw.githubusercontent.com/commonmark/commonmark-java/main/LICENSE.txt
	<td>✅ ["BSD-2-Clause"]
	<td>✅ ["BSD-2-Clause"]
<tr>
	<td>Apache-2.0 OR GPL-3.0
    <td>Concatenated text from URLs above
	<td>✅ ["GPL-3.0-only" "GPL-3.0" "Apache-2.0" "GPL-3.0-or-later" "GPL-3.0+"]
	<td>✅ []

This seems correct to me, since matchingStandardLicenseIds() doesn't match multi-license texts.
<tr>
	<td>CDDL-1.1 OR GPL-2.0 WITH Classpath-exception-2.0 (JavaMail)
    <td>https://raw.githubusercontent.com/javaee/javamail/master/LICENSE.txt
	<td>❌ []
	<td>✅ []

This seems correct to me, since matchingStandardLicenseIds() doesn't match multi-license texts.
</table>

I _think_ that some of these failures (e.g. CC-BY-4.0) may be due to problems with the templates rather than anything specific to the code, but haven't double checked that.

**Comment by goneall** [comment]
@pmonks - Thanks for the testing.  Looks like there is still some work to do, but we're getting closer.

> https://creativecommons.org/licenses/by/4.0/legalcode.txt

I use the [license diff utility](https://github.com/spdx/spdx-license-diff) on the page and there are a few differences, but it should be handled by the templates.

> https://www.mozilla.org/media/MPL/2.0/index.txt

This doesn't surprise me - I think the templates for both of these are almost the same.

> https://raw.githubusercontent.com/javaee/javamail/master/LICENSE.txt

I couldn't get the license diff util to work on this page (maybe too long?) so I couldn't do a quick analysis.

**Pull request merged**
