### PR TITLE
add license black list & white list detect function in LicenseCompareHelper

### PR DESCRIPTION
**Pull request by XenoAmess**
add 2 functions to LicenseCompareHelper

### CODE REVIEW

**Comment by goneall** [comment]
There is a possibility that one of the children licenses in a `ConjunctiveLicenseSet` is also a `ConjunctiveLicenseSet`.  To cover this case, you'll need to recursively descend the entire tree of licenses.

There is a similar, but rarer corner case for `DisjunctiveLicenseSets` where the children all contain white or black list items.

**Comment by goneall** [comment]
Once other request - could this be implemented without the additional dependency?  I'm trying to keep the dependencies to a minimum.

**Comment by XenoAmess** [comment]
> There is a possibility that one of the children licenses in a `ConjunctiveLicenseSet` is also a `ConjunctiveLicenseSet`. To cover this case, you'll need to recursively descend the entire tree of licenses.

@goneall 

I think it is actually recursively now...

Can you provide some failing test cases? Thanks!

**Comment by XenoAmess** [comment]
> Once other request - could this be implemented without the additional dependency? I'm trying to keep the dependencies to a minimum.

OK

**Comment by goneall** [comment]
> I think it is actually recursively now...

Yes - you are correct.  Sorry I missed that on my first review of the code.

**Comment by goneall** [comment]
Thanks @XenoAmess - Nice addition to the library!

**Pull request merged**
