### PR TITLE
Initial implementation of issue 141

### PR DESCRIPTION
**Pull request by pmonks**
This is an initial implementation of issue #141 (add support for multi-license texts to license comparison logic).

### CODE REVIEW

**Comment by goneall** [comment]
Thanks @pmonks - Could you sign-off your commits - or you could also just add add a comment to this PR that you agree to the licensing section of the CONTRIBUTING.md file:  https://github.com/spdx/Spdx-Java-Library/blob/master/CONTRIBUTING.md#licensing

Also - one of the checks in the CI is complaining about a possible null pointer exception - on line https://github.com/spdx/Spdx-Java-Library/blob/180f4a5ac83614f30a7a11f4dd22251aa9c78f76/src/main/java/org/spdx/utility/compare/LicenseCompareHelper.java#L858

An easy fix would be to add a check at the beginning of the method - something like:

```
	public static boolean isStandardLicenseWithinText(String text, SpdxListedLicense license) {
               if (license == null || if text == null) {
                    return false;
                 }
		// Get match status
		boolean result = false;
		int startIndex = -1;
```

If you want to add that to the PR, that would be great.

**Comment by pmonks** [comment]
@goneall I fixed the linter issue, and signed that final commit as well. I held off on rebasing all of my earlier commits to sign them, as I've been merging from `master` as you worked there in parallel, and didn't want to accidentally sign your interleaved commits (git makes this kind of thing way too difficult / error-prone, but I digress...).

Regardless, I assert here that all of my earlier commits were developed personally by me, and that they meet the requirements of [CONTRIBUTING.md#licensing](https://github.com/spdx/Spdx-Java-Library/blob/master/CONTRIBUTING.md#licensing).

**Comment by pmonks** [comment]
@goneall Note that the "1 new bug" detected by @sonatype-lift above is a false positive.  `license` cannot be null on [line 863](https://github.com/spdx/Spdx-Java-Library/blob/99c365a4e6bdadc30f7578cc25c28d6919ef22b8/src/main/java/org/spdx/utility/compare/LicenseCompareHelper.java#L863) because of the guard on [line 858](https://github.com/spdx/Spdx-Java-Library/blob/99c365a4e6bdadc30f7578cc25c28d6919ef22b8/src/main/java/org/spdx/utility/compare/LicenseCompareHelper.java#L858).

**Comment by goneall** [comment]
Thanks @pmonks  - I'll go ahead and merge this in.

BTW - I run into similar false positives on the linter from time to time.

**Pull request merged**
